### ISSUE TITLE
Update information on requesting updated CDN cert using 2022, 2023 procedures

### ISSUE THREAD

**Issue by jdiverp** [UWIT-IAM/gcp-docs#6]
https://github.com/UWIT-IAM/gcp-docs/blob/1db666beb04be30a1d1b84fee52dedb45e2ed0e4/new-cdn.md?plain=1#L92-L99

From 12/11/2023 meeting. Jonathan to update this document with current (currently used) process to update CDN cert.

**Comment by soufianerafik** [comment]
[gcp-docs/new-cdn.md](https://github.com/UWIT-IAM/gcp-docs/blob/1db666beb04be30a1d1b84fee52dedb45e2ed0e4/new-cdn.md?plain=1#L92-L99) was updated in [gcp-docs#PR-8](https://github.com/UWIT-IAM/gcp-docs/pull/8), will close this issue.
